import { SxProps } from "@mui/material";
import {
  EmptyDataValues,
  EmptyExtracredValuesType,
  PlaceType,
  StateType,
} from "./types";

export const defaultGap = 0.75;
export const marginBottomDefault = 2;

export const containerSxProps: SxProps = {
  gap: defaultGap,
  mb: marginBottomDefault,
  p: 0.5,
  pt: 1,
};

export const emptyExtractedValues: EmptyExtracredValuesType = {
  travelers: {
    id: "",
    name: "",
    age: "",
    info: "",
    passport: "",
    preferences: [],
  },
  hotels: {
    id: "",
    address: "",
    checkin_date: "",
    checkin_time: "",
    checkout_date: "",
    checkout_time: "",
    description: "",
    guests: [],
    info: "",
    loc_ref: "",
    name: "",
    room_type: "",
    timezone: "",
  },
  flights: {
    id: "",
    arrival_airport: "",
    arrival_date: "",
    arrival_loc_ref: "",
    arrival_time: "",
    arrival_timezone: "",
    baggage: "",
    booking_reference: "",
    flight_number: "",
    departure_airport: "",
    departure_date: "",
    departure_loc_ref: "",
    departure_time: "",
    departure_timezone: "",
    class_type: "",
    company_name: "",
  },
  bus_trains: {
    id: "",
    arrival_address: "",
    arrival_date: "",
    arrival_loc_ref: "",
    arrival_time: "",
    arrival_timezone: "",
    company_name: "",
    departure_address: "",
    departure_date: "",
    departure_loc_ref: "",
    departure_time: "",
    departure_timezone: "",
    destination: "",
    info: "",
    origin: "",
    seats: [],
    ticket_reference: "",
    travel_number: "",
    travelers: [],
    type: "bus",
  },
  car_rents: {
    id: "",
    car_category: "",
    car_description: "",
    driver: "",
    dropoff_address: "",
    dropoff_date: "",
    dropoff_loc_ref: "",
    dropoff_time: "",
    dropoff_timezone: "",
    info: "",
    name: "",
    pickup_address: "",
    pickup_date: "",
    pickup_loc_ref: "",
    pickup_time: "",
    pickup_timezone: "",
  },
  events: {
    id: "",
    address: "",
    address_loc_ref: "",
    begin_time: "",
    date: "",
    info: "",
    name: "",
    seats: [],
    timezone: "",
    travelers: [],
  },
};

export const stateEmptyValues: EmptyDataValues = {
  places_data: {
    id: "",
    address: "",
    latitude: "",
    longitude: "",
    map_url: "",
    name: "",
    photos: [],
    place_id: "",
    reference: [],
    timezone: "",
    type: "",
    types: [],
  },
  destination_data: {
    id: "",
    name: "",
    country: "",
    brief: "",
    reference: "",
    highlights: [],
    map_url: "",
    address: "",
    type: "",
  },
};

export const emptyState: StateType = {
  extracted_data: {
    travelers: [],
    bus_trains: [],
    car_rents: [],
    events: [],
    flights: [],
    hotels: [],
  },
  destination_data: [],
  places_data: [],
  problem_data: { problem_data: [] },
  what_to_pack_data: { what_to_pack_data: [] },
};
